import { Button, Container, Title } from '@mantine/core';
import { type NextPageWithLayout } from 'next';
import Head from 'next/head';
import { useState } from 'react';

import { api } from '~/utils/api';

const Home: NextPageWithLayout = () => {
	const hello = api.example.hello.useQuery({ text: 'from tRPC' });
	const users = api.example.dbTest.useQuery();
	const [clickCount, setClickCount] = useState(0);

	return (
		<>
			<Head>
				<title>Shop - NANYAN</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Container size="xl">
					<Title order={3}>{hello.data?.greeting}</Title>
					<Button onClick={() => setClickCount((c) => c + 1)}>
						Clicked: {clickCount}
					</Button>
					<pre>{JSON.stringify({ users }, null, 4)}</pre>
				</Container>
			</main>
		</>
	);
};

export default Home;
